package ir.abrang.accounting;
import android.Manifest;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.MediaStore;import android.webkit.*;import android.widget.Toast;import java.io.*;import java.nio.charset.StandardCharsets;
public class MainActivity extends Activity{
 WebView w; ValueCallback<Uri[]> fileCb; String saveName,saveText,saveMime; static final int FILE=9001,STORE=9002;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xff182941);getWindow().setNavigationBarColor(0xff182941);w=new WebView(this);setContentView(w);WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);if(Build.VERSION.SDK_INT>=21)s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);
 w.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return ext(r.getUrl());}@Override public boolean shouldOverrideUrlLoading(WebView v,String u){return ext(Uri.parse(u));}});
 w.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCb!=null)fileCb.onReceiveValue(null);fileCb=cb;try{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,FILE);return true;}catch(Exception e){fileCb=null;return false;}}});
 w.addJavascriptInterface(new Bridge(),"Android");w.loadUrl("file:///android_asset/index.html");
 }
 boolean ext(Uri u){String s=u.getScheme();if(s==null||s.equals("file")||s.equals("about"))return false;if(s.equals("http")||s.equals("https"))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){}return true;}
 public void saveTextFile(String n,String t,String m){if(n==null||n.isEmpty())n="abrang-export.txt";n=n.replaceAll("[\\\\/:*?\"<>|]","_");if(Build.VERSION.SDK_INT>=29)try{ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,n);v.put(MediaStore.Downloads.MIME_TYPE,m==null?"text/plain":m);v.put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS+"/ABRANG");Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(u==null)throw new Exception();try(OutputStream o=getContentResolver().openOutputStream(u)){o.write((t==null?"":t).getBytes(StandardCharsets.UTF_8));}toast("فایل در Downloads/ABRANG ذخیره شد");}catch(Exception e){toast("ذخیره فایل ناموفق بود");}else{saveName=n;saveText=t==null?"":t;saveMime=m;if(checkSelfPermission(Manifest.permission.WRITE_EXTERNAL_STORAGE)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE},STORE);else legacy();}}
 void legacy(){try{File d=new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),"ABRANG");d.mkdirs();try(FileOutputStream o=new FileOutputStream(new File(d,saveName))){o.write(saveText.getBytes(StandardCharsets.UTF_8));}toast("فایل در Downloads/ABRANG ذخیره شد");}catch(Exception e){toast("ذخیره فایل ناموفق بود");}}
 @Override public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);if(r==STORE&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)legacy();}
 class Bridge{@JavascriptInterface public void saveTextFile(String n,String t,String m){MainActivity.this.saveTextFile(n,t,m);}@JavascriptInterface public void toast(String s){MainActivity.this.toast(s);}@JavascriptInterface public String platform(){return "android";}}
 void toast(String s){runOnUiThread(()->Toast.makeText(this,s,Toast.LENGTH_SHORT).show());}
 @Override public void onBackPressed(){if(w!=null&&w.canGoBack())w.goBack();else super.onBackPressed();}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==FILE&&fileCb!=null){Uri[]x=null;if(c==RESULT_OK&&d!=null&&d.getData()!=null)x=new Uri[]{d.getData()};fileCb.onReceiveValue(x);fileCb=null;}}
 @Override protected void onDestroy(){if(w!=null){w.stopLoading();w.destroy();}super.onDestroy();}
}